<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>false</PublishSingleFile>
    <StartupObject>Clip.Desktop.Program</StartupObject>
    <AssemblyName>Clip</AssemblyName>
    <RootNamespace>Clip.Desktop</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Clip.Core/Clip.Core.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(GITHUB_REPOSITORY)' == 'OXeu/clip' And '$(GITHUB_WORKFLOW)' == 'Windows build'">
    <AssemblyMetadata Include="GitHubSha" Value="$(GITHUB_SHA)" />
    <AssemblyMetadata Include="GitHubRunNumber" Value="$(GITHUB_RUN_NUMBER)" />
    <AssemblyMetadata Include="GitHubRunAttempt" Value="$(GITHUB_RUN_ATTEMPT)" />
  </ItemGroup>
</Project>
